services:
  servidor_caronas:
    build:
      context: .
      dockerfile: Dockerfile.servidor
    container_name: servidor_caronas_container
    ports:
      - "8080:8080"
    volumes:
      # Modificado: Agora aponta para uma subpasta, sem sobrescrever o binário em /app
      - ./dados_persistentados:/app/dados
    restart: always
